### ISSUE TITLE
Failed to validate array

### ISSUE THREAD

**Issue by bistory** [creatoro/jelly#101]
Hi !

I'm testing Jelly with Jelly auth on Ko 3.2.
I was using the good old jelly before and decided to go forward.
But I'm experiencing a problem regarding validation.

The complete error is visible here : http://imgur.com/uJsFT

Is it a bug in Jelly or in Jelly Auth ? How can I fix it ?

Thanks :)

**Comment by leth** [comment]
Look at the [validation rules for the auth user definition](https://github.com/creatoro/jelly-auth/blob/3.2/master/classes/model/auth/user.php).

`$user->save()` will perform validation before saving, and throw an exception if it is invalid.
Have you tried calling `errors()` on the exception object? i.e. `$e->errors()`.

My suspicion is that you didn't fill in a username field.

**Comment by bistory** [comment]
Thanks, you are right, I didn't implement user because I don't need it. I will change the model :)
