### ISSUE TITLE
Hashing performe before validation in Jelly_Field_Password

### ISSUE THREAD

**Issue by artad** [creatoro/jelly#103]
I want to reopen issue #44. I have the same problem. And I think I know  why.
```// Add a filter that hashes the password when validating
   $this->filters[] = array(array(':field', 'hash'), array(':value', ':model'));

```
Hash function sets as filter and filters work on set, before validation.

It is no errors if you define only rules not_empty and min_lenght because hash from not empty field is not empty and always have more then 10 chars lenght. 

But if you try to define max_lenght rule you will get an error. 
```

**Comment by creatoro** [comment]
Validation checks should be done externally for passwords. Please see the guide's Validation page and External validation seciton. Or check out the Auth driver's validation: https://github.com/creatoro/jelly-auth/blob/3.2/master/classes/model/auth/user.php#L89
