### ISSUE TITLE
Update class structure

### ISSUE THREAD

**Issue by Lokaltog** [creatoro/jelly#15]
I was thinking about making Jelly more Kodoc-friendly by updating comment headers and restructuring the project class structure to be more like the Kohana project and other modules. I.e. renaming all `Jelly_Core_*` classes to `Kohana_Jelly_*` and separating classes with `@category` tags. I recently did this to another project I'm working on, and I really think the folder structure is more logical and easier to understand.

A structure change like this will not change anything for the end user, because it only changes the extended classes.

What do you guys think about this? I'd be happy to perform the update if others agree.

**Comment by leth** [comment]
I'm not sure if it's a good idea to be putting everything under `Kohana_` as this isn't an official module.

Generally it's bad practice to coin identifiers in someone else's namespace (or in one you don't control).

I'd advise getting one of the core Kohana devs to weigh in here.

**Comment by creatoro** [comment]
I'm with leth on this one. Even Kohana devs, like Shadowhand tend to use `Modulename_Core` in their modules. It would be nice to have conventions for creating modules.

I will start a discusson about this in the forum.

**Comment by creatoro** [comment]
I'm closing this issue until the Kohana devs have something to say regarding [this topic](http://dev.kohanaframework.org/issues/3922).
