### ISSUE TITLE
$_with not behaving expectedly

### ISSUE THREAD

**Issue by coreyworrell** [creatoro/jelly#16]
When setting `protected $_with = array('role')`, I would expect it to perform a join, but instead it just selects `model.role_id AS model.role`.

Ideally, I think doing this:
    $user = Jelly::query('user', 1)->select();
Should always add that join when `$_with` is set, so essentially doing this behind the scenes:
    $user = Jelly::query('user', 1)->with('role')->select();

**Comment by creatoro** [comment]
Use `$meta->load_with('role');` when defining your models. I've updated the guide with an example for this, check out the `Defining models` part.

**Comment by coreyworrell** [comment]
Aaaah okay. Great, thanks!
