### ISSUE TITLE
Wrong boolean format after setting

### ISSUE THREAD

**Issue by creatoro** [creatoro/jelly#17]
See issue [here](https://github.com/kohana-world/kohana-jelly/issues/2).
Credit goes to [biakaveron](https://github.com/biakaveron).

**Comment by creatoro** [comment]
Closed by 99d04d8773cc62c1e54e4ed6c442176854fa4f79.

**Comment by creatoro** [comment]
The previous fix caused more trouble than good, so it was reverted until a proper solution is found.

**Comment by biakaveron** [comment]
What kind of troubles you have?

**Comment by creatoro** [comment]
Well, this is odd. When I applied your fix it seemed that it caused tests to fail. But checking it now it looks OK. Must have been my bad... 

However, there's a twist: the fix got back somehow after the revert, so it's actually in the code. But checking it now with your test gives me an update query every time it saves the model, so it causes the very same problem it was created for. And reverting it to the original code (`return $value;`) solves the problem. Makes me puzzled...

Can you check it out?
