### ISSUE TITLE
Can i use jelly on live production

### ISSUE THREAD

**Issue by dexcell** [creatoro/jelly#19]
Hi, just wanted to know if it's (pretty)stable to use this on my new live project?

Thank you

**Comment by creatoro** [comment]
I'm using it on a live project without serious problems, most of the important bugs are fixed now. I have a few pending fixes for smaller bugs, but those are not really critical.

I'm not going to take any responsibility, but if you do enough testing you should be fine :).

**Comment by dexcell** [comment]
Thank you, creatoro :)

I was waiting for jelly stable release and want to use it for next project but unfortunately jonathan resigned, so i am very glad that you maintaining this library.
I hope you can push this great library to stable release, so everyone can start use it on live project without hesitation :)
