### ISSUE TITLE
Multiple BelongsTo joins doesn't work

### ISSUE THREAD

**Issue by misterx** [creatoro/jelly#20]
When relation name difference of table name, we have error in Jelly::alias();. Example:
I used your models from jelly-test, and change relation "role", to "action" in User model.

```
'action' => new Field_BelongsTo(array(
            'default' => 0,
            'foreign' => 'role'
        )),
```

Then:

```
Jelly::select('author')->with('action')->limit(1)->execute(); //This working fine;
```

But this:

```
Jelly::select('post')->with('author:action')->limit(1)->execute(); //Have error, cose Jelly search "action" as model.
```

When i try fix this problem, I came to that, architecture must be changed, cose Field_BelongsTo->with .. don't know about previous relations, and can't build valid aliases for the relation model

**Comment by creatoro** [comment]
You are using old syntax that is not supported now, please check out the latest version of [Jelly](https://github.com/creatoro/kohana-jelly-for-Kohana-3.1) and [Jelly tests](https://github.com/creatoro/jelly-tests-for-Kohana-3.1) and report back.

**Comment by misterx** [comment]
My fail, i copied old ticket from jonathangeiger repo, but i try this in new version.
    jelly::query('material')->with('author:user')->limit(1)->select();
and have same problem.
Schema:

Model "material": table - "news_materials", relation "author" - belongsto model "material_author"

Model "material_author": table - "news_authors", relation "user" - belongsto model "core_user"

model "core_user": table - "core_user"

**Comment by misterx** [comment]
In your test you can try this:
    jelly::query('test_post')->with('approved_by:role')->limit(1)->select();
But need next changes:
In model 'author', add relation:
    'role' => Jelly::field('belongsto', array(
                'foreign' => 'test_role.id',
                'column'  => 'trole_id',
            )),
When relation name, don't equal model name

**Comment by creatoro** [comment]
Thanks, I will look into it. Until then if somebody else has a fix it's welcome.

**Comment by creatoro** [comment]
A really dirty fix just to see where's the problem and how would it work.
Any suggestion is welcome on how to do this properly.

Change [line 703](https://github.com/creatoro/kohana-jelly-for-Kohana-3.1/blob/3.1%2Fdevelop/classes/jelly/core/builder.php#L703) to this:
`$origin = $parent = $this->_meta->model();`

Add this before [line 743](https://github.com/creatoro/kohana-jelly-for-Kohana-3.1/blob/3.1%2Fdevelop/classes/jelly/core/builder.php#L743):

```
        if ($parent !== $this->_model)
        {
            $this->_model = $parent;
            $field->model = $origin.':'.$field->model;
        }
```

**Comment by misterx** [comment]
This must work as method `with`, in ko3 [ORM::with](https://github.com/kohana/orm/blob/3.1%2Fmaster/classes/kohana/orm.php#L829). In Jelly i see problem with aliases, cose join alias for last relation `role`, must be ':test_role:approved_by:role', but method `with` in `belongsto_field`, don't know about a previous chain of aliases.
P.S. This dirty fix, don't work for me =(

**Comment by creatoro** [comment]
@misterx: what error did you get with the dirty fix applied?

**Comment by misterx** [comment]
`ErrorException [ Notice ]: Trying to get property of non-object
MODPATH\jelly\classes\jelly\core\builder.php [ 853 ]`

**Comment by misterx** [comment]
sorry for close =)

**Comment by misterx** [comment]
sorry, after fix line #  858 
     $model = Jelly::meta($parent)->field($field)->foreign['model'];

**Comment by leth** [comment]
Try applying this patch instead, and let me know if it helps, it sounds like it might be related
https://github.com/creatoro/kohana-jelly-for-Kohana-3.1/pull/48

**Comment by creatoro** [comment]
@leth: thanks for all your contrubutions, I'm away until next week, I'll review everything then.

Just checked your patch and unfortunately it won't fix this bug. I think I'll apply my dirty fix as it does work (even when your pull request is applied) and I'll close this issue with a 'Review later' label.

**Comment by creatoro** [comment]
@misterx: can you check if this solved your problem?

**Comment by misterx** [comment]
no, this don't work =( has a same error 
<code>
ErrorException [ Notice ]: Trying to get property of non-object
MODPATH\jelly\classes\jelly\core\builder.php [ 884 ]
</code>

**Comment by creatoro** [comment]
@misterx:

When I tested the fix I used `Model_Test_Post`, `Model_Test_Author` and `Model_Test_Role` from [jelly-tests](https://github.com/creatoro/jelly-tests-for-Kohana-3.1).

`Model_Test_Post` belongs to `Model_Test_Author` and `Model_Test_Author` belongs to `Model_Test_Role`.

I have commented out the `load_with()` line in `Model_Test_Post` as this would cause an error.

Then I used this line of code which resulted in a successful query (I got the same error with this as you did before the fix):

```
Jelly::query('test_post')->with('test_author:test_role')->select();
```

**Comment by leth** [comment]
This is tricky to debug. If you have the time, you could fork the jelly-tests repo and make a test case for us :)

**Comment by misterx** [comment]
I try to make test case, but have a problem, i don't use git, i can write this, and send via email or other communication =)

**Comment by misterx** [comment]
@creatoro, @leth:
No problem  if  your relation name same as model name. But if u use different relation name, you must have error. Try to rename relation.

**Comment by leth** [comment]
@misterx: You can post things to github here: https://gist.github.com/

@creatoro:
I think I've found what might be the problem:

The `field->with(..)` method doesn't know the alias that it should use for the table.
It works fine for chains of one item, or for relationships which happen to be named well.

I think the builder needs to pass the chain string to the with method [here](https://github.com/creatoro/kohana-jelly-for-Kohana-3.1/blob/3.1%2Fdevelop/classes/jelly/core/builder.php#L771).

Also: I think the `with` call would be better /before/ the `select(...` loop, because then it can populate the _model_aliases cache before select_column tries to.

Edit: wrong link.

**Comment by leth** [comment]
I've [added some test cases for this](https://github.com/leth/jelly-tests/commit/5618ea56f30b92b6d2e3c2e86016437a9aa82818), and [rewritten the with() method, and tweaked the _model_alias() method](https://github.com/leth/kohana-jelly/commit/cea1045d4a39ff886cb8be96ac4eb26397e02609).

@misterx: This should fix your problems :)

@creatoro: Before applying the fix, the test case won't succeed unless you disable the automatic 'with' configured on the test_post model, because nothing checks that you don't join the same field twice.

**Comment by creatoro** [comment]
@leth: pull request merged in 6c8b64714f53c403e226c1bf98dfde19d0ed8a1f, thanks a lot!

@misterx: you should test it now and see if it works.

**Comment by leth** [comment]
Don't forget to merge the tests :)

**Comment by creatoro** [comment]
Will do :).

**Comment by creatoro** [comment]
@misterx: any progress?

**Comment by misterx** [comment]
Hi, sorry for my late answer. Thats great, and working very good for me! Thanks
This bug traveled from the first Jelly version =) And now @leth fix it =) My respect!
