### ISSUE TITLE
add load function to jelly builder

### ISSUE THREAD

**Issue by dexcell** [creatoro/jelly#23]
select() function always return Jelly_Collection
load() function always return Jelly_Model

I think it's better leave to developer to decide which return type he would like to use, instead using automated result type based on limit(1). 

syntax example 

```
// Get all posts
$posts = Jelly::query('post')->select();
// Get first post
$post = Jelly::query('post')->load();
// Get jelly model post
$post = Jelly::query('post')->where('title', '=', 'hello')->load();
```

This is useful when limit variable is based on user input. 
For example

```
// Get post limit from url
$limit = (int) $this->request->get('limit');
// Get all posts
$posts =  Jelly::query('post')->limit($limit)->select();
// Show all post
foreach ($posts as $post)
{
    echo $post->text;
}
```

The code above wouldn't have problem even limit is 1, but it would have problem for current syntax since it would return jelly model instead of jelly collection.

And i think it's easy for developer to decide when he would like to use load or select.
It's just like find() and find_all() in official ORM module.

Thank you

**Comment by leth** [comment]
I see the point you're making there, iirc it used to be in jelly but got removed.
It might be worth seeing if anyone can remember why, I know Jon is busy with other things, but @banks might remember.

**Comment by dexcell** [comment]
Yes, there is explanation in the migration guide.
But syntax above  is little different from previous one. I don't mind if there is no load() function since current() function will return same result.
But developer should have freedom and control which result he want to get. (kohana way)

To fix this we just need to delete this code below from jelly builder select method

```
// If the record was limited to 1, we only return that model
// Otherwise we return the whole result set.
if ($this->_limit === 1)
{
    $this->_result = $this->_result->current();
}
```

if we want to add load() function:

```
public function load($db = NULL)
{
    return $this->select($db)->current();
}
```

**Comment by creatoro** [comment]
I see why would you need `Jelly_Collection` in this example, but can you guys tell me a situation when you would always need to return `Jelly_Model`?

**Comment by dexcell** [comment]
For example filtering unique field such as username

```
// Since we know username unique we don't need Jelly Collection
Jelly::query('user')->where('username', '=', 'creatoro')->load();
// But if you want to do it with limit, well it's developer freedom
Jelly::query('user')->where('username', '=', 'creatoro')
    ->limit(1)
    ->select()
    ->current();
```

**Comment by dexcell** [comment]
or
    Jelly::query('user')->where('username', '=', 'creatoro')
        ->limit(1)
        ->load();

**Comment by creatoro** [comment]
What do you think about this:

```
public function select($db = NULL, $auto_return = TRUE)
{
    //...

    // If the record was limited to 1 and we are allowed to make an automated 
    // decision we only return that model
    // Otherwise we return the whole result set.
    if ($this->_limit === 1 AND $auto_return === TRUE)
    {
        $this->_result = $this->_result->current();
    }

    return $this->_result;
}
```

If you want to force returning a `Jelly_Model` you can always do that by setting `limit(1)` and leaving the automated switch set to `TRUE`.

This way we don't need a new method.

**Comment by leth** [comment]
Or if you're selecting by primary key and expect only one result.

**Comment by leth** [comment]
That doesn't seem as elegant to me.
I prefer the original proposal, it'd make for cleaner code.

**Comment by dexcell** [comment]
@creatoro
That's nice but it would be producing ugly code (like sprig) for example
    $user = Jelly::query('user')->where('username', '=', 'creatoro')->select(NULL, FALSE):

so the previous solution is the best although we need to ctrl-replace limit(1)->select() in jelly auth.

@leth
Yes, that's also one of the case.

**Comment by banks** [comment]
Hi guys, I can't remember the original rationale for the magic behaviour - I think it was assumed that there would not be a case where you would intentionally limit to 1 and expect multiple results but frankly looking over this I agree that it is unnecessary magic more likely to confuse and limit than save much time.

For what it's worth given that I don't really have a professional interest in Jelly any more, I think just delete the magic is the best solution and use `->select()->current()`. A `load()` function saves a single function call in pretty rare cases and IMO just adds more stuff to the API that serves to confuse. I know Jon spent a long time trying to keep API method names as close to SQL as possible so it would be intuitive to read and not have to think about exactly what a function did (`select()` runs a 'SELECT' query e.t.c.).

But I guess if people like `load()` it's hardly a monstrosity! I would urge you to consider calling it `select_first()` or similar though since `load()` is somewhat ambiguous as to why it differs from `select()`.

My $0.02

**Comment by dexcell** [comment]
@banks
I agree with you, the limit magic return should be deleted. Yeah probably it's best not to include load() function so we can keep the api method close to sql.

select_first() seems not good. i think we should use force developer to use select()->current() if he want to select the first select result. That way it's still very clean code and readable.

What do you think creatoro?

**Comment by dexcell** [comment]
Just dig into another problem..
The belongs to field relies on the limit(1) magic function result..
So if we delete it, syntax below won't work

```
$post->user->username;
```

because $post->user will return Jelly Collection instead of Jelly Model

```
// This will work tough it's ugly...
$post->user->current()->username;
```

I think It would need to change the structure to fix this....

**Comment by creatoro** [comment]
Nice to see @banks here :).
It seems that going the `select()->current()` way would be the cleanest solution, but as @dexcell pointed out this change would require other changes as well, not to mention everybody needs to change their code to have it behave as it should.

Let's give this a bit more thought...

**Comment by leth** [comment]
I'm in favour of `load()` over `select()->current()`.

The difference between the two would be that `load()` could enforce the `LIMIT 1`, whereas `select()->current()` would not.
In most cases, the SQL server would have to do a lot more work if you have a large DB table and missed off a `LIMIT 1`.

**Comment by leth** [comment]
By 'in most cases' I mean when your where conditions do not select among unique fields or composite fields in a way where the SQL server can optimise the query to assume there will only be one result.

**Comment by creatoro** [comment]
I think adding a new method will be the way to go. I would prefer not to mess with changing a whole lot of code because of modifying `select()` to always return the same object.

I think it would be better to call the new method `select_all()` instead of `load()` or something else.

To summarize it:
- `select_all()` would always return `Jelly_Collection`
- `select()` would keep the automated behavior
- to force returning `Jelly_Model` one can use `limit(1)` before `select()`

Any opinions against the new method name or the way it would work?

**Comment by leth** [comment]
I think `select_all()` is a good choice, better than `load()`, it makes it clear that things are plural and the name is still close to SQL.

**Comment by creatoro** [comment]
As there were no other suggestions I'm going to implement the `select_all()` method soon.

**Comment by dexcell** [comment]
How about this:

select() always return Jelly_Model
select_all() always return Jelly_Collection

But probably another bug will appear, if we changed like syntax like above. i haven't test it yet.

Anyway for the long term i think we shouldn't have function that magically change the result type based on limit(1)
I don't know if we have to change the structure to achieve this.

**Comment by creatoro** [comment]
@dexcell: it might be a good idea to remove the magic method, but this way we won't have to do structural changes at the moment. Let's take one step at a time and later we can review this subject.

**Comment by dexcell** [comment]
@creatoro
Yes, i think it's the best option for now.
