### ISSUE TITLE
Is it possible to get hasmany->hasmany with jelly?

### ISSUE THREAD

**Issue by dexcell** [creatoro/jelly#26]
For example
user has many posts, post has many comments

Is it possible with jelly to do thing like this?

```
//Get all comments by user
$user->posts->comments;
```

**Comment by paulchubatyy** [comment]
AFAIK this is not supported out-of-the-box but may be easily implemented with `Jelly_Builder`. See [the gist](https://gist.github.com/917533) for implementation. Then you may retrieve the comments like this:

  Jelly::select('comments')->get_user_posts_comments($author);

Also you may define the customer method in our `Model_Author`:

```
public function get_posts_comments()
{
    return Jelly::select('comments')->get_user_posts_comments($this)
        ->execute();
}
```

So I do not think it should be bundled in jelly itself.

**Comment by graphis** [comment]
I tried out the jelly builder method, but does not work for me.
The last time I managed to work with the jelly builder was with the orgiginal jelly branch

Kohana_Exception [ 0 ]: Invalid method do_something_method called on class Jelly_Builder

**Comment by creatoro** [comment]
@graphis: I don't think your issue is related. Please post your code to [this forum topic](http://forum.kohanaframework.org/discussion/8069/jelly-for-kohana-3.1-auth-driver-included) for help.

**Comment by creatoro** [comment]
It might be a better idea to add a small tutorial in the guide on how to do this manually then having this in the core. What do you guys think?

**Comment by dexcell** [comment]
@xobb
Yes it's possible with extra method, but it would be nice to have them build in the core.

imagine you can get thing like this out of the box:
$user->posts->categories->posts->comments;

**Comment by paulchubatyy** [comment]
@dexcell
Yeah, that would be very-very-very-super-kool. But most of the projects don't need this functionality. So, I'm all for adding the proper docs.

**Comment by leth** [comment]
Hang on, does this not do it out of the box?

```
Jelly::query('comments')->with('post:user')->select();
```

It relies on there being the corresponding opposite relationships for your has-many ones.
