### ISSUE TITLE
Wrong class extensions

### ISSUE THREAD

**Issue by loonies** [creatoro/jelly#29]
It's impossibile to use benefits of Kohana's CFS without completly overloading classes.

The whole module should be reviewed for this issues.

file:
**classes/jelly/core/builder.php**

replace:
`abstract class Jelly_Core_Builder extends Kohana_Database_Query_Builder_Select`

with:
`abstract class Jelly_Core_Builder extends Database_Query_Builder_Select`

file:
**classes/jelly/core/field/image.php**

replace:
`abstract class Jelly_Core_Field_Image extends Jelly_Core_Field_File`

with:
`abstract class Jelly_Core_Field_Image extends Jelly_Field_File`

**Comment by creatoro** [comment]
@loonies: use the default 3.1/develop branch, `Jelly_Core_Field_Image` is already fixed in that branch. I'll fix the other, thanks for reporting.

edit: I took a quick look at all the extensions and haven't found other issues like this.

**Comment by loonies** [comment]
Ah.. thx I didn't notice that, it's an old project, so I can't update easily  :)

**Comment by creatoro** [comment]
Actual fix: bc9f258a41dbbf9b63b86c2039eac58a4d6557e8.
The previous one accidentally had some experimental code in it...
