### ISSUE TITLE
Rewrite the Field_Image class

### ISSUE THREAD

**Issue by loonies** [creatoro/jelly#30]
The current implementation of the Field_Image class is bloated and should be rewrited.

You can find my proposal in the [3.1/develop-creatoro-unstable](https://github.com/loonies/kohana-jelly/blob/3.1%2Fdevelop-creatoro-unstable/classes/jelly/core/field/image.php) branch (relevant commit loonies/kohana-jelly@440ed18a9e94f659083616b2f80ef001a8809afb), just to get an idea.

Note: I did this before #24, so didn't took related changes into account

**Comment by creatoro** [comment]
Thanks!
Looks nice, but I wouldn't continue [using the tranformed image](https://github.com/loonies/kohana-jelly/blob/3.1%2Fdevelop-creatoro-unstable/classes/jelly/core/field/image.php#L146) to create thumbnails. Using the original would give the user more freedom.

Also: there's an optional validation [check for dimensions](https://github.com/loonies/kohana-jelly/blob/3.1%2Fdevelop-creatoro-unstable/classes/jelly/core/field/image.php#L124), but that runs after the original was uploaded, so I don't really see the point using it. Am I missing something?

**Comment by loonies** [comment]
1. Yeah... I think you're right, my first thought was to reduce memory consuption by using "smaller" image for creating the thumbnails, but now I realize that user could apply some complex transformation to the main image and make it unusable for creating the thumbnails.
2. Dimension check is there to prevent PHP runing out of memory when processing the image with big resolution. When that happens PHP will not throw any exception or error and will just die silently.
   I already thought about that before and I think this check should be separeted into validation method, just like [UNIQUE check](https://github.com/creatoro/kohana-jelly-for-Kohana-3.1/blob/3.1%2Fdevelop/classes/jelly/core/field.php#L265).

**Comment by creatoro** [comment]
I'm nearly finished modding your version, I'll implement a validation check just like the one you mentioned.

**Comment by creatoro** [comment]
@loonies: checking the width and height of the temporary uploaded image doesn't seem to be possible, so the dimension check needs to be run after the upload of the original is completed. I would rather leave this feature out... Any ideas?

**Comment by loonies** [comment]
Maybe we should leave this feature out for now. (I'll look at this when I catch some time :))
