### ISSUE TITLE
Field_File::_upload should always return boolean

### ISSUE THREAD

**Issue by loonies** [creatoro/jelly#31]
The current implementation of `Field_File::_upload` is inconsistent. Namely, `Field_File::_upload` will sometimes return the Validation object and sometimes boolean. Classes that use this method (e.g. Field_Image) can't rely on this  implementation (see [Field_Image@L126](https://github.com/creatoro/kohana-jelly-for-Kohana-3.1/blob/3.1%2Fdevelop/classes/jelly/core/field/image.php#L126)).

Fix here loonies/kohana-jelly@6437a6cc370557e171e68baf8eeb7fb028028ce6

**Comment by creatoro** [comment]
Thanks.
