### ISSUE TITLE
Image set without upload

### ISSUE THREAD

**Issue by marcalj** [creatoro/jelly#34]
Hi, I want to upload a photo (ultra big photo) but save in the database with Jelly with a CRON.

When I set the image as string of their path it never validates.

For example: "/home/ddd/image.jpg" or "image.jpg".

If I create a fake $_FILES object, the function "is_uploaded_file" doesn't pass.

There's a way to accomplish that?

Thanks.

**Comment by creatoro** [comment]
You don't have to create a fake $_FILES array, just set the image to the name of the file and save it without validation:

```
$image = Jelly::factory('image');
$image->filename = 'bigphoto.jpg';
$image->save(FALSE);
```

Next time please post your question to the [forum](http://forum.kohanaframework.org/discussion/8069/jelly-for-kohana-3.1-auth-driver-included).

**Comment by marcalj** [comment]
Sorry, I thought it might be a bug.
Thanks for the reply.

**Comment by creatoro** [comment]
I see, no problem though :).
