### ISSUE TITLE
Alias building while order_by

### ISSUE THREAD

**Issue by p00h** [creatoro/jelly#41]
There is a method <strong>_field_alias</strong> in <strong>classes/jelly/core/builder.php</strong>

``` php
        // Alias to the column
        if ($meta = Jelly::meta($model) AND $field_obj = $meta->field($field) AND $field_obj->in_db)
        {
            $column = $field_obj->column;

            // We're 99% sure adding the table name in front won't cause problems now
            $join = $join_if_sure ? TRUE : $join;
        }

        return $join ? $alias.'.'.$column : $column;
```

In case of order_by method adds table_name to returning value and, for example,

<pre>column_name</pre>

becomes

<pre>table_name.column_name</pre>

but table prefix wont be added later, so we'll recieve a query like this:

``` sql
SELECT `table_prefix_table`.`field` FROM `table_prefix_table` ORDER BY `table`.`field`
```

so query fails

Is it a jelly bug?

**Comment by creatoro** [comment]
Can you show me your exact query?
Also, are you using the **3.1/develop** branch?

**Comment by p00h** [comment]
``` sql
SELECT
    `cf_jelly_nodes`.`name` AS `name` ,
    `cf_jelly_nodes`.`position` AS `position` ,
    `cf_jelly_nodes`.`pyramid_id` AS `pyramid_id` ,
    `cf_jelly_nodes`.`funds` AS `funds` ,
    `cf_jelly_nodes`.`activity` AS `activity` ,
    `cf_jelly_nodes`.`clone_of` AS `clone_of` ,
    `cf_jelly_nodes`.`clones_count` AS `clones_count` ,
    `cf_jelly_nodes`.`joined` AS `joined` ,
    `cf_jelly_nodes`.`lft` AS `left` ,
    `cf_jelly_nodes`.`rgt` AS `right` ,
    `cf_jelly_nodes`.`lvl` AS `level` ,
    `cf_jelly_nodes`.`scope` AS `scope`
FROM `cf_jelly_nodes` AS `cf_jelly_nodes`
WHERE `cf_jelly_nodes`.`pyramid_id` =1
ORDER BY `jelly_nodes`.`position` ASC
```

Im using 3.1/develop branch
Query built using regular jelly way. Table prefix is `cf_`. And it applies to all parts of query except `order_by`

Backtrace:

```
modules/database/classes/kohana/database/mysql.php:181
modules/database/classes/kohana/database/query.php:225
modules/jelly-creatoro/classes/jelly/core/builder.php:147
modules/jelly-creatoro/classes/jelly/core/builder.php:296
```

**Comment by p00h** [comment]
And if I replace

```
return $join ? $alias.'.'.$column : $column;
```

with

```
return $column;
```

query executes correctly

**Comment by p00h** [comment]
Would it be correct to replace

```
    public function order_by($column, $direction = NULL)
    {
        return parent::order_by($this->_field_alias($column), $direction);
    }
```

with

```
    public function order_by($column, $direction = NULL)
    {
        return parent::order_by($this->_field_alias($column, NULL, FALSE), $direction);
    }
```

?

**Comment by p00h** [comment]
Working under. It seems the problem is more deeper.

**Comment by creatoro** [comment]
This is strange. I tested this with my users table with a query like this:

`Jelly::query('user')->where('id', '=', 1)->order_by('logins', 'ASC')->select();`

I couldn't replicate the issue, the result looks OK:

```
SELECT
    `pf_users`.`id` AS `id`,
    `pf_users`.`email` AS `email`,
    `pf_users`.`username` AS `username`,
    `pf_users`.`password` AS `password`,
    `pf_users`.`logins` AS `logins`,
    `pf_users`.`last_login` AS `last_login`,
    `pf_users`.`twitter_id` AS `twitter_id`,
    `pf_users`.`facebook_id` AS `facebook_id`
FROM `pf_users` AS `pf_users`
WHERE `pf_users`.`id` = 1
ORDER BY `pf_users`.`logins` ASC
```

**Comment by p00h** [comment]
I see. Im still working hard under, and i'm quite sure the problem sits in my code. But please do not close issue until i find the decision!

**Comment by p00h** [comment]
Bug found. It was fully my fault. Please excuse me for any inconvenience.

**Comment by creatoro** [comment]
Glad you found the problem. Could you please explain your bug and the solution for the record and close the issue if that's done?

**Comment by creatoro** [comment]
@p00h: I'm closing this, but if you have the time please details your problem and solution.

**Comment by p00h** [comment]
The problem does not apply to jelly at all!
When i've tested my application with quite simple business logic I realized that queries builds correctly.
Then after 20 hours of debugging i found very small bug and problem disappeared.
