### ISSUE TITLE
Deleting related records in HasOne and HasMany associations

### ISSUE THREAD

**Issue by macieklamberski** [creatoro/jelly#42]
Hi!

Is there any possibility to set that the objects linked to the current object (by HasOne or HasMany association) were automatically deleted when current object is? I mean something like what you can find in ActiveRecord in Rails. (`has_many :news, :dependent => :destroy`).

If not, it would be nice if this functionality was implemented into Jelly. It could be declared like this:

```
'news' => Jelly::field('HasMany', array(
  'foreign' => 'news.author_id',
  'dependent' => 'destroy', // Rails-ish way to do this
)),
```

**Comment by TdroL** [comment]
Are you using MySQL? If yes, use InnoDB engine and make proper relations between tables.

**Comment by macieklamberski** [comment]
Yeah, I know. But I'm not much of a database guy and it would be nice to have such relationships declared at the application level.

It would be possible to quickly create models, relationships and their dependencies, without digging into the database on each of the environments. The code would be more flexible and portable between environments and different types of databases.

**Comment by creatoro** [comment]
I'm not really into putting new things like this into Jelly as it adds more magic to the code, but sounds like a nice feature to have. I'll think it through, if anyone has comments or suggestions they're welcome.

If this gets implemented it should be strictly optional and the code shouldn't modify the current workings of Jelly, just extend it and it should be bypassed by default.
