### ISSUE TITLE
Automatically deleting files when deleting an object

### ISSUE THREAD

**Issue by macieklamberski** [creatoro/jelly#43]
Referring to previous issue (#42) a good thing would be to be able to set that all uploaded files related to the currently deleted object will be deleted as well.

There are two fields that deal with handling file upload - `Jelly_Field_Image` and `Jelly_Field_Field`. My suggestion is to add additional property to each of them, that if set to TRUE will be responsible for deleting files when removing an object. As files, I mean:
- `Jelly_Field_File`: file associated with this field
- `Jelly_Field_Image`: pictures of all sizes

It should also be checked whether it is access to deleted files in case they didn't exist or was no access to them.

**Comment by creatoro** [comment]
If #42 gets implemented I don't see why we shouldn't have this as well.
