### ISSUE TITLE
Hashing performe before validation in Jelly_Field_Password

### ISSUE THREAD

**Issue by Sharom** [creatoro/jelly#44]
Hashing performe before validation in Jelly_Field_Password.
Therefore, we get incorrect validation results .

**Comment by creatoro** [comment]
Validation checks should be done externally for passwords. Please see the guide's Validation page and External validation seciton. Or check out the Auth driver's validation: https://github.com/creatoro/jelly-auth/blob/3.2/master/classes/model/auth/user.php#L89
