### ISSUE TITLE
Loading behavior with the same name as model

### ISSUE THREAD

**Issue by macieklamberski** [creatoro/jelly#49]
When creating query, Jelly automatically loads the builder (if exists) with the same name as the model. Have you thought about creating a similar mechanism for behaviors?

**For example**:
We have a model `Model_Product` and related builder called `Jelly_Behavior_Product`. Now, while instantiating `Model_Product` (`Jelly::factory('Product')`, `Jelly::query('Product')` etc.) mechanism described above would look if there is a behavior called `Jelly_Behavior_Product` and automatically load if exists. This would release us from the obligation to manually append `$meta->behaviors(array(new Jelly_Behavior_Product))` in the model's `initialize` method.

**Comment by creatoro** [comment]
This sounds nice, I'll think about it.
