### ISSUE TITLE
Jelly_Field_Image - transformations from one thumbnail applies to other

### ISSUE THREAD

**Issue by macieklamberski** [creatoro/jelly#55]
We have Image field with defined two or more thumbnails.

```
'image' => Jelly::field('image', array(
    'transformations' => array(
        'resize' => array(880, 200, Image::INVERSE),
        'crop' => array(880, 200),
    ),
    'thumbnails' => array(
        array(
            'prefix' => 'small_',
            'transformations' => array(
                'resize' => array(220, 50, Image::AUTO),
            ),
        ),
        array(
            'prefix' => 'cropped_',
            'transformations' => array(
                'crop' => array(250, 200),
            ),
        ),
    ),
)),
```

Then, while uploading a file, each thumbnail is generated not from the main image file, but from the image transformed by thumbnails defined before current. In the above example, last thumbnail will cropped from image with applied `'resize' => array(220, 50, Image::AUTO),` transformation from previous "small_" thumbnail.

Is this intentional behavior? I think that each thumbnail should be generated from the base image (with applied main transformations), independently of the other thumbnails.

**Comment by creatoro** [comment]
This isn't intentional, in fact it should be working as you described it. Fix coming soon.

**Comment by creatoro** [comment]
@lamberski: can you report back after a test?

**Comment by macieklamberski** [comment]
It's working good now. Thanks! :)
