### ISSUE TITLE
Return value of _upload method in Jelly_Field_File and Jelly_Field_Image should be always boolean

### ISSUE THREAD

**Issue by creatoro** [creatoro/jelly#56]
See title.

**Comment by Neurergus** [comment]
Hello creatoro,

I'm having problems with this change. 

If "_upload" returns FALSE, the validation process seems to ignore the 'manual setted' errors (ex: $validation->error($field, 'invalid_file')) and only shows the error message modelname._upload.

To solve this, I had to revert this commit, changing 'return FALSE' to 'return', leaving 'return TRUE' and modifying Jelly_Field_Image to check for the TRUE value in parent::_upload. 

Also, I moved the portion of code that checks if the file is valid (types) to before the check of $validation->errors. In my case, when I show the error list, I want to show all the possible information :)

Any drawbacks to this 'solution'?
