### ISSUE TITLE
Listing with joins

### ISSUE THREAD

**Issue by Gamec** [creatoro/jelly#57]
I want to make a list of posts with authors. So I've made a "belongsto" relationships in post model, but when I'm listing them Jelly generates additional select queries for every post (to get author's data). 

Is it possible to generate just one query like: SELECT posts._, authors._ FROM posts p JOIN authors a ON (a.id = p.author_id)?

**Comment by creatoro** [comment]
Use the `load_with()` method when defining a model. Check out the sample model in the [guide](https://github.com/creatoro/kohana-jelly-for-Kohana-3.1/blob/3.1%2Fdevelop/guide/jelly/getting-started/defining-models.md).

Next time please post questions to the [forum](http://forum.kohanaframework.org/discussion/8069/jelly-for-kohana-3.1-auth-driver-included).
