### ISSUE TITLE
Text is not String!

### ISSUE THREAD

**Issue by ckald** [creatoro/jelly#59]
I'm updating Migrate module for your Jelly version. I have to say, i had some troubles with your logics :)

Jelly_Core_Field_Text extends Jelly_Core_Field_String — and all my text fields appear in db like strings. Please, fix it. Simply copy string-field implementation.

Thanks

**Comment by creatoro** [comment]
@ckald: these are not my logics, as it was like this when I forked Jelly from John and I think it's done the right way. I'm open to changes, but I'm not sure if I understand your intentions.

Is your problem with using `instanceof` in your module to check the type of the field?

Also, what implementation were you referring to?

**Comment by creatoro** [comment]
@ckald: any comments on this?

**Comment by creatoro** [comment]
@ckald: I'm closing this, feel free to reopen it if you have to say something.
