### ISSUE TITLE
Kohana 3.2 branch

### ISSUE THREAD

**Issue by leth** [creatoro/jelly#63]
Since 3.2 is out, I think a 3.2/develop branch is in order :)
I've only spotted one incompatibility so far (I've not had time to run the tests) and there's a fix for it in my fork.

**Comment by creatoro** [comment]
Thanks! I'll create it as soon as I have some time to close all the open issues. I'm a bit busy with a project atm.

**Comment by leth** [comment]
## No problem! Hope they're going well

Sent from my phone.

creatoro reply@reply.github.com wrote:

Thanks! I'll create it as soon as I have some time to close all the open issues. I'm a bit busy with a project atm.

##

**Comment by leth** [comment]
I've update my branch; all the tests pass on the 3.2 branch. :)

**Comment by marcalj** [comment]
Good work! :)

**Comment by creatoro** [comment]
@leth: great! :)
I've got some serious S.O.S. work to do, after that I'll merge everything.

**Comment by creatoro** [comment]
Main compatibility issues solved by:
- Issue #80: 8fa90d8447f21999e4c189a4fd2279d960a08e69
- Issue #81: c1abf4ce3545ab7e31239777263299c819f9b632
- Issue #83: d9a2113fdfdad38ff9d287f778352d84bee11221

3.2/develop branch is ready for development.
