### ISSUE TITLE
Easier way to change database connection

### ISSUE THREAD

**Issue by loonies** [creatoro/jelly#69]
There should be an easier way to change DB connection (e.g. for testing). Right now, it is not possibile to change DB connection if model is already _initialized_.

The only way around:
- extend Jelly_Meta and do some voodoo for switching DB connection
- extend every model and set DB connection there <=> PITA

**Comment by creatoro** [comment]
Can you show me a testing example where this might be actually useful?

ATM the database connection for testing is chosen by checking the `db_connection` in the unit test module's configuraiton (_APPATH/config/unittest.php_). Isn't that sufficent?

**Comment by creatoro** [comment]
@loonies: any ideas?

**Comment by loonies** [comment]
I'm busy ATM, please leave this open, I'll get back to it.

**Comment by marcalj** [comment]
Sorry I have not yet migrated all the code from Sprig to Jelly because I have a project with 3 databases...
Can you leave open for 3.2 branch? So I will have time to study it also.

**Comment by creatoro** [comment]
What about having a config file for setting which db connection to use?
As default we would still use the ˛`Database::$default` value, but this way it's easily changed.

The config file would use Kohana's environment types, so the database connection could be set for:
- PRODUCTION
- STAGING
- TESTING
- DEVELOPMENT

If you all think that this solution is OK, then the last question remains is how to structure the config file.

Method 1:

```
return array
(
    Kohana::PRODUCTION => array(
        // Database connection for production, define in database config
        'connection' => Database::$default,
    ),
    Kohana::STAGING => array(
        // Database connection for staging, define in database config
        'connection' => Database::$default,
    ),
    Kohana::TESTING => array(
        // Database connection for testing, define in database config
        'connection' => Database::$default,
    ),
    Kohana::DEVELOPMENT => array(
        // Database connection for development, define in database config
        'connection' => Database::$default,
    ),
);
```

Method 2 (I prefer this one, more readable and I don't expect a lot of environment-dependable config variables in the future):

```
return array
(
    // Database connection
    'connection' => array(
        Kohana::PRODUCTION  => Database::$default,
        Kohana::STAGING     => Database::$default,
        Kohana::TESTING     => Database::$default,
        Kohana::DEVELOPMENT => Database::$default,
    ),
);
```

Edit: I already have this working, so if you are happy, then I'm happy with this.

**Comment by marcalj** [comment]
I think my case is more simple that I expected. I have the database config (`config/database.php`) returning array depending of environment, and in each array there's all different db's I use.

So if in the Model I can set wich db name is, I'm happy. After all I'm using `DB::` class and select the database on `execute()` method... but I'm not study it very consciously.

I think this feature is for very specific environments and I think @loonies want to change the database after initialization. So I'm not sure if your solution is a duplication of setting this in the main database config (`config/database.php`)...

**Comment by creatoro** [comment]
@marcalj: yeah, @loonies did speak about changing the DB after initialization, but I would rather not touch that part ATM.

However, having this config file would allow to us to have cleaner testing code as we don't have to set the DB everywhere and it would be a nice addition as it wouldn't require anybody to change their code, but it makes having different settings for environments easy (and we can't rely on having environment-based DB connections set up in the main DB config file).

**Comment by marcalj** [comment]
Ok nice.

**Comment by creatoro** [comment]
I did some benchmarks for getting the default db name from `Database::$default` vs config file.
On the long run `Database::$default` is about 53% faster (100-10000 calls), but when using only one call they are about the same (they finish in 0.000015s-0.000020s).

The question is: is this speed difference neglible or not?

**Comment by creatoro** [comment]
After thinking this through again this would only help removing some additional code from the unit tests and it wouldn't really solve the issue @loonies came up with.

For tests let's do what the [Kohana team does](http://dev.kohanaframework.org/issues/3677).

For anything else? Do we even need to have the ability to change the db after initialization?

**Comment by creatoro** [comment]
@loonies: as you're who opened the issue, could you comment on this?

**Comment by loonies** [comment]
Yes, I was talking about changing DB connection after model initialization. Honestly, I don't remember any more where I got this issue. Anyway, you can close this AFAIC, I'll deal with this later if I'll have to.

**Comment by creatoro** [comment]
Ok, if we don't have to work on the alias feature (or other things) I'm creating the master branch and we have Jelly 1.0.
