### ISSUE TITLE
Jelly::query sort_by bug

### ISSUE THREAD

**Issue by marcalj** [creatoro/jelly#72]
In a model, if I set default sorting in meta: `$meta->sorting(array('name' => 'asc'));` then, when I use: `Jelly::query('company')->order_by('name', 'desc');` doesn't work. It uses always the default `meta` config.

**Comment by creatoro** [comment]
@marcalj: please check this again as I couldn't reproduce your issue. Everything seems to be fine with the latest updates.

**Comment by marcalj** [comment]
Finally I found the bug! It's related to `count()` method.

If I set the `order_by` manually **before** a `count()` (pagination), for some reason it gets cleared. If I set it **after**, works perfect.

I use the order by method after a pagination count because it is irrelevant the order for the count.

In Jelly_Builder class, line 289:

``` php
        // Start with a basic SELECT
        $query = $this->_build(Database::SELECT)->as_object(FALSE);

        // Dump a few unecessary bits that cause problems
        $query->_select = $query->_order_by = array();
```

Note that `$query->_order_by` is cleared from the query, but probably the solution is to construct an independent query to just count the records, and leave the original as is.

Markdown is going crazy!

**Comment by creatoro** [comment]
The `count()` method deletes the order by statement from the query, it doesn't matter if it's set automatically or manually. There is no `ORDER BY` in the query when using `count()`.

This is the intended working of the method and I see no reason to change it.

I don't know how you did it, but setting `order_by()` after `count()` will throw an exception, so it shouldn't be possible.

**Comment by marcalj** [comment]
Mmmm... when I calculate the pagination I use `count()` and then `limit()` and `offset()`, after that I was setting `order_by()`, and doesn't work, but any exception is thrown.

I need to set order by before the pagination logic to work.

I'm not saying that code should be changed, I'm just saying that when you clear `$query->_order_by = array();` seems to do also `$this->_order_by = array();`.

**Comment by creatoro** [comment]
There's no way to add order by after `count()` (if you are assigning that to a variable then continue to work with that variable), because it's like a the `select()` method, it executes the query. So I would recommend building the query like this for pagination (in the example I use the Pagination module):

```
    // Build query
    $query = Jelly::query('post')->where('published', '=', 1);

    // Set up pagination
    $pagination = Pagination::factory(array(
        'total_items'    => $query->count(),
        'items_per_page' => 20,
    ));

    // Set limit and offset
    $query->limit($pagination->items_per_page);
    $query->offset($pagination->offset);

    // Execute the query, in other words select the posts
    $posts = $query->select();
```

**Comment by marcalj** [comment]
Ok, it's how I do, but I think that will be awesome to can call `count()` and do not affect the current query at all.
