### ISSUE TITLE
Jelly_Model is_new() function

### ISSUE THREAD

**Issue by marcalj** [creatoro/jelly#76]
When playing with behaviors, the function `model_before_save` needs a way to know if a save will be an INSERT or an UPDATE.

So I propose this function:

``` php
    /**
     * Check if model is new (looking for a key).
     *
     * @return bool
     */
    public function is_new()
    {
        return (bool) ! $this->_original[$this->_meta->primary_key()];
    }
```

**Comment by marcalj** [comment]
Well we can use `id()` function for the same purpose?

Which way is more reliable?

**Comment by creatoro** [comment]
As you have the model object in the `model_before_save($model)` method it's just a matter of using this:

```
if ($model->loaded())
{
    // We are updating
}
else
{
    // We are inserting
}
```

**Comment by marcalj** [comment]
I'm not sure, because for some reason you can not load a model and updating their values... is it possible? (if not, can be a good feature for optimizing SQL calls).

For example:

```
$model = Jelly::factory('post');
$model->id = 4;
$model->title = 'test';
$model->save(); // It has to be an update
```

**Comment by creatoro** [comment]
You have to load the model before updating it with the `save()` method. Earlier it was possible to update models without having to load them, but this feature was deleted by Jon.

**Comment by marcalj** [comment]
:(
