### ISSUE TITLE
Can't use functions like UPPER in where clause

### ISSUE THREAD

**Issue by xtazz** [creatoro/jelly#86]
Queries like this: `Jelly::query('table')->...->where('UPPER(table.field_name)','IN',$field_values)`
are resulting in following SQL code: `...WHERE `UPPER(table`.`field_name)` IN ('VALUE1', 'VALUE2')`

This code is causing MySQL to fail query because ` are incorrectly placed for such where clauses.

If it's Kohana issue, please let me know, I'll resubmit this bug to them.

Thanks!

Best Regards,
Peter

**Comment by leth** [comment]
Try using a DatabaseExpression object. Look up the kohana docs for `DB:expr(...)`.

**Comment by xtazz** [comment]
Thanks much! Now it works okay
