### ISSUE TITLE
Bug in Jelly_Core_Field_ManyToMany

### ISSUE THREAD

**Issue by macieklamberski** [creatoro/jelly#91]
I think there is a bug in `Jelly_Core_Field_ManyToMany` class in `get()` method. On line 138 it should be:

```
->where($this->foreign['field'], 'IN', $value);
```

instead of:

```
->where($this->foreign['column'], 'IN', $value);
```

because `column` index is no longer used as it has been replaced by `field`.

**Comment by creatoro** [comment]
Well spotted, thanks! Stupid mistake...
